export const PAESI_LIST = [
    { value: "AF", description: "Afghanistan" },
    { value: "AL", description: "Albania" },
    { value: "DZ", description: "Algeria" },
    { value: "AS", description: "American Samoa" },
    { value: "AD", description: "Andorra" },
    { value: "AO", description: "Angola" },
    { value: "AI", description: "Anguilla" },
    { value: "AQ", description: "Antartide" },
    { value: "AG", description: "Antigua e Barbuda" },
    { value: "SA", description: "Arabia Saudita" },
    { value: "AR", description: "Argentina" },
    { value: "AM", description: "Armenia" },
    { value: "AW", description: "Aruba" },
    { value: "AU", description: "Australia" },
    { value: "AT", description: "Austria" },
    { value: "AZ", description: "Azerbaijan" },
    { value: "BS", description: "Bahamas" },
    { value: "BH", description: "Bahrain" },
    { value: "BD", description: "Bangladesh" },
    { value: "BB", description: "Barbados" },
    { value: "PW", description: "Belau" },
    { value: "BE", description: "Belgio" },
    { value: "BZ", description: "Belize" },
    { value: "BJ", description: "Benin" },
    { value: "BM", description: "Bermuda" },
    { value: "BT", description: "Bhutan" },
    { value: "BY", description: "Bielorussia" },
    { value: "MM", description: "Birmania" },
    { value: "BO", description: "Bolivia" },
    { value: "BQ", description: "Bonaire, Saint Eustatius e Saba" },
    { value: "BA", description: "Bosnia-Erzegovina" },
    { value: "BW", description: "Botswana" },
    { value: "BR", description: "Brasile" },
    { value: "BN", description: "Brunei" },
    { value: "BG", description: "Bulgaria" },
    { value: "BF", description: "Burkina Faso" },
    { value: "BI", description: "Burundi" },
    { value: "KH", description: "Cambogia" },
    { value: "CM", description: "Camerun" },
    { value: "CA", description: "Canada" },
    { value: "CV", description: "Capo Verde" },
    { value: "TD", description: "Ciad" },
    { value: "CL", description: "Cile" },
    { value: "CN", description: "Cina" },
    { value: "CY", description: "Cipro" },
    { value: "CO", description: "Colombia" },
    { value: "KM", description: "Comore" },
    { value: "CG", description: "Congo (Brazzaville)" },
    { value: "CD", description: "Congo (Kinshasa)" },
    { value: "KP", description: "Corea del Nord" },
    { value: "KR", description: "Corea del Sud" },
    { value: "CI", description: "Costa d'Avorio" },
    { value: "CR", description: "Costa Rica" },
    { value: "HR", description: "Croazia" },
    { value: "CU", description: "Cuba" },
    { value: "CW", description: "Curaçao" },
    { value: "DK", description: "Danimarca" },
    { value: "DM", description: "Dominica" },
    { value: "EC", description: "Ecuador" },
    { value: "EG", description: "Egitto" },
    { value: "SV", description: "El Salvador" },
    { value: "AE", description: "Emirati Arabi Uniti" },
    { value: "ER", description: "Eritrea" },
    { value: "EE", description: "Estonia" },
    { value: "SZ", description: "Eswatini" },
    { value: "ET", description: "Etiopia" },
    { value: "FJ", description: "Figi" },
    { value: "PH", description: "Filippine" },
    { value: "FI", description: "Finlandia" },
    { value: "FR", description: "Francia" },
    { value: "GA", description: "Gabon" },
    { value: "GM", description: "Gambia" },
    { value: "GE", description: "Georgia" },
    { value: "DE", description: "Germania" },
    { value: "GH", description: "Ghana" },
    { value: "JM", description: "Giamaica" },
    { value: "JP", description: "Giappone" },
    { value: "GI", description: "Gibilterra" },
    { value: "DJ", description: "Gibuti" },
    { value: "JO", description: "Giordania" },
    { value: "GR", description: "Grecia" },
    { value: "GD", description: "Grenada" },
    { value: "GL", description: "Groenlandia" },
    { value: "GP", description: "Guadalupa" },
    { value: "GU", description: "Guam" },
    { value: "GT", description: "Guatemala" },
    { value: "GG", description: "Guernsey" },
    { value: "GN", description: "Guinea" },
    { value: "GQ", description: "Guinea Equatoriale" },
    { value: "GW", description: "Guinea-Bissau" },
    { value: "GY", description: "Guyana" },
    { value: "GF", description: "Guyana Francese" },
    { value: "HT", description: "Haiti" },
    { value: "HN", description: "Honduras" },
    { value: "HK", description: "Hong Kong" },
    { value: "IN", description: "India" },
    { value: "ID", description: "Indonesia" },
    { value: "IR", description: "Iran" },
    { value: "IQ", description: "Iraq" },
    { value: "IE", description: "Irlanda" },
    { value: "IS", description: "Islanda" },
    { value: "BV", description: "Isola Bouvet" },
    { value: "IM", description: "Isola di Man" },
    { value: "CX", description: "Isola di Natale" },
    { value: "NF", description: "Isola Norfolk" },
    { value: "AX", description: "Isole Åland" },
    { value: "KY", description: "Isole Cayman" },
    { value: "CC", description: "Isole Cocos (Keeling)" },
    { value: "CK", description: "Isole Cook" },
    { value: "FK", description: "Isole Falkland" },
    { value: "FO", description: "Isole Faroe" },
    { value: "HM", description: "Isole Heard e McDonald" },
    { value: "MH", description: "Isole Marshall" },
    { value: "SB", description: "Isole Salomone" },
    { value: "VI", description: "Isole Vergini Americane" },
    { value: "VG", description: "Isole Vergini Britanniche" },
    { value: "IL", description: "Israele" },
    { value: "IT", description: "Italia" },
    { value: "JE", description: "Jersey" },
    { value: "KZ", description: "Kazakistan" },
    { value: "KE", description: "Kenya" },
    { value: "KG", description: "Kirghizistan" },
    { value: "KI", description: "Kiribati" },
    { value: "KW", description: "Kuwait" },
    { value: "LA", description: "Laos" },
    { value: "LS", description: "Lesotho" },
    { value: "LV", description: "Lettonia" },
    { value: "LB", description: "Libano" },
    { value: "LR", description: "Liberia" },
    { value: "LY", description: "Libia" },
    { value: "LI", description: "Liechtenstein" },
    { value: "LT", description: "Lituania" },
    { value: "LU", description: "Lussemburgo" },
    { value: "MO", description: "Macao" },
    { value: "MK", description: "Macedonia del Nord" },
    { value: "MG", description: "Madagascar" },
    { value: "MW", description: "Malawi" },
    { value: "MY", description: "Malaysia" },
    { value: "MV", description: "Maldive" },
    { value: "ML", description: "Mali" },
    { value: "MT", description: "Malta" },
    { value: "MA", description: "Marocco" },
    { value: "MQ", description: "Martinica" },
    { value: "MR", description: "Mauritania" },
    { value: "MU", description: "Mauritius" },
    { value: "YT", description: "Mayotte" },
    { value: "MX", description: "Messico" },
    { value: "FM", description: "Micronesia" },
    { value: "MD", description: "Moldavia" },
    { value: "MC", description: "Monaco" },
    { value: "MN", description: "Mongolia" },
    { value: "ME", description: "Montenegro" },
    { value: "MS", description: "Montserrat" },
    { value: "MZ", description: "Mozambico" },
    { value: "NA", description: "Namibia" },
    { value: "NR", description: "Nauru" },
    { value: "NP", description: "Nepal" },
    { value: "NI", description: "Nicaragua" },
    { value: "NE", description: "Niger" },
    { value: "NG", description: "Nigeria" },
    { value: "NU", description: "Niue" },
    { value: "MP", description: "Northern Mariana Islands" },
    { value: "NO", description: "Norvegia" },
    { value: "NC", description: "Nuova Caledonia" },
    { value: "NZ", description: "Nuova Zelanda" },
    { value: "OM", description: "Oman" },
    { value: "NL", description: "Paesi Bassi" },
    { value: "PK", description: "Pakistan" },
    { value: "PA", description: "Panama" },
    { value: "PG", description: "Papua Nuova Guinea" },
    { value: "PY", description: "Paraguay" },
    { value: "PE", description: "Perù" },
    { value: "PN", description: "Pitcairn" },
    { value: "PF", description: "Polinesia Francese" },
    { value: "PL", description: "Polonia" },
    { value: "PT", description: "Portogallo" },
    { value: "PR", description: "Puerto Rico" },
    { value: "QA", description: "Qatar" },
    { value: "GB", description: "Regno Unito (UK)" },
    { value: "CZ", description: "Repubblica Ceca" },
    { value: "CF", description: "Repubblica Centrafricana" },
    { value: "DO", description: "Repubblica Dominicana" },
    { value: "RE", description: "Reunion" },
    { value: "RO", description: "Romania" },
    { value: "RU", description: "Russia" },
    { value: "RW", description: "Rwanda" },
    { value: "EH", description: "Sahara Occidentale" },
    { value: "SH", description: "Saint Helena" },
    { value: "KN", description: "Saint Kitts e Nevis" },
    { value: "LC", description: "Saint Lucia" },
    { value: "MF", description: "Saint Martin (Francia)" },
    { value: "SX", description: "Saint Martin (Paesi Bassi)" },
    { value: "VC", description: "Saint Vincent e Grenadine" },
    { value: "BL", description: "Saint-Barthélemy" },
    { value: "PM", description: "Saint-Pierre e Miquelon" },
    { value: "WS", description: "Samoa" },
    { value: "SM", description: "San Marino" },
    { value: "ST", description: "São Tomé e Príncipe" },
    { value: "SN", description: "Senegal" },
    { value: "RS", description: "Serbia" },
    { value: "SC", description: "Seychelles" },
    { value: "SL", description: "Sierra Leone" },
    { value: "SG", description: "Singapore" },
    { value: "SY", description: "Siria" },
    { value: "SK", description: "Slovacchia" },
    { value: "SI", description: "Slovenia" },
    { value: "SO", description: "Somalia" },
    { value: "GS", description: "South Georgia/Sandwich Islands" },
    { value: "ES", description: "Spagna" },
    { value: "LK", description: "Sri Lanka" },
    { value: "US", description: "Stati Uniti (US)" },
    { value: "UM", description: "Stati Uniti (US) Isole Minori" },
    { value: "ZA", description: "Sud Africa" },
    { value: "SD", description: "Sudan" },
    { value: "SS", description: "Sudan del Sud" },
    { value: "SR", description: "Suriname" },
    { value: "SJ", description: "Svalbard e Jan Mayen" },
    { value: "SE", description: "Svezia" },
    { value: "CH", description: "Svizzera" },
    { value: "TJ", description: "Tagikistan" },
    { value: "TH", description: "Tailandia" },
    { value: "TW", description: "Taiwan" },
    { value: "TZ", description: "Tanzania" },
    { value: "TF", description: "Terre Australi e Antartiche Francesi" },
    { value: "PS", description: "Territori palestinesi" },
    { value: "IO", description: "Territorio Britannico dell'Oceano Indiano" },
    { value: "TL", description: "Timor Est" },
    { value: "TG", description: "Togo" },
    { value: "TK", description: "Tokelau" },
    { value: "TO", description: "Tonga" },
    { value: "TT", description: "Trinidad e Tobago" },
    { value: "TN", description: "Tunisia" },
    { value: "TR", description: "Turchia" },
    { value: "TM", description: "Turkmenistan" },
    { value: "TC", description: "Turks e Caicos" },
    { value: "TV", description: "Tuvalu" },
    { value: "UA", description: "Ucraina" },
    { value: "UG", description: "Uganda" },
    { value: "HU", description: "Ungheria" },
    { value: "UY", description: "Uruguay" },
    { value: "UZ", description: "Uzbekistan" },
    { value: "VU", description: "Vanuatu" },
    { value: "VA", description: "Vaticano" },
    { value: "VE", description: "Venezuela" },
    { value: "VN", description: "Vietnam" },
    { value: "WF", description: "Wallis e Futuna" },
    { value: "YE", description: "Yemen" },
    { value: "ZM", description: "Zambia" },
    { value: "ZW", description: "Zimbabwe" },
]