server:
  servlet:
    context-path: /backend
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commercialista
    username: postgres
    password: 1305
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtps.aruba.it
    port: 465
    username: no_reply@devmind360.com
    password: Felino9797!
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        debug: true

configuration:
  app:
    jwtSecret: "======================Commerci=alista=========================="
    jwtExpirationMs: 86400000

logging:
  level:
    root: INFO
    com:
      commercialista: DEBUG
    org:
      hibernate: INFO
      hibernate.SQL: DEBUG
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Europe/Rome"
  file-appender:
    enabled: true
  config: classpath:logback-spring.xml
  file:
    name: logs/commercialista-be

custom:
  
  email:
    base-url-server-for-content: https://www.devmind360.com:8443/backend
    no-response-email: no_reply@devmind360.com
    support-email: support@devmind360.com
    content:
      logo-in-email: /logoA.png
      bg-banner: /bg_banner.jpg
      bollino-sito: /bolloAI.png
      info-icon: /info-icon.png
    support-send-message-panel-subject: LaTuaCommercialista - Messaggio
  
  site:
    name: LaTuaCommercialista
    domain: LaTuaCommercialista.com
  
  server:
    frontend:
      base-url: http://localhost:4200
    backend:
      base-url: http://localhost:8080
  
  scheduler:
    enable: false
